### ISSUE TITLE
中文题目换行 \\&换行后，后续目录无法生成，pdf也只能生成部分内容

### ISSUE THREAD

**Issue by QiangzhenZhu** [YanMing-lxb/GUET_Thesis_LaTeX#16]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by YanMing-lxb** [comment]
好的，我已经修改了这个问题，已经上传了，你可以测试一下
后面我也发现盲审封面也存在类似的问题，这个我稍后改一下

**Comment by QiangzhenZhu** [comment]
这修复速度。佬牛逼的

**Comment by YanMing-lxb** [comment]
盲审版论文封面的题目中插入 `\\&` 命令会导致编译失败的问题我也解决了，可以下载最新的发行版了
