### ISSUE TITLE
您好，guet学校官网交论文要求word格式，有没有比较好的方式，将latex转为word

### ISSUE THREAD

**Issue by QiangzhenZhu** [YanMing-lxb/GUET_Thesis_LaTeX#17]
老哥，有啥好办法吗？

**Comment by YanMing-lxb** [comment]
是本科还是研究生？我是23年毕业的研究生，学校好像没有强制要求用word的吧，可以提交pdf的啊，我就是全程提交的pdf，查重送审都是。不过本科的我就不太清楚了。能详细告诉我是啥原因吗，或者写有这个要求的网址或文件发给我看看。

如果是转成word，可以用pandoc，但是论文中插入的pdf图片转换后word中会显示空白，另外交叉引用会失效，参考文献的引用可能也会实效，文字倒是没问题。另外你也可以尝试使用wps将latex生成的pdf转换成word。

pandoc的转换命令，可以看 [LaTeX转Word命令.md](https://github.com/YanMing-lxb/YM-VSCode-Configurations-for-LaTeX/blob/main/Docs/LaTeX%E8%BD%ACWord%E5%91%BD%E4%BB%A4.md)

**Comment by QiangzhenZhu** [comment]
是研究生，我看终版论文上传那里有 word 和 pdf 版本上传，系统好像是新版系统。
<img width="1196" alt="1709042659428" src="https://github.com/YanMing-lxb/GUET_Thesis_LaTeX/assets/31847579/8b571de9-c70b-4620-916a-b2da7fd21047">

**Comment by YanMing-lxb** [comment]
word应该不是必选的吧，可以不上传吧，实在不行的话，你就问一下教学秘书，总不能从头再从word排版一次。
我感觉应该不是必须要word，你明天问一下教学秘书

**Comment by QiangzhenZhu** [comment]
好的，感谢老哥，我明天问一下

**Comment by YanMing-lxb** [comment]
嗯嗯，有消息的话，告诉我一下

**Comment by QiangzhenZhu** [comment]
《各位同学，近期有不少学生咨询最终提交的盲审论文版本是PDF还是WORD或者两个都提交，有很多同学都是使用的latex来写学位论文，目前根据新系统上的界面显示是有PDF和WORD两个版本都要提交的地方，所以在正式通知还未下发之前请同学们提前准备好word和PDF两个版本的盲审论文，盲审封面请在研究生院官网下载，谢谢。》  目前，学校的规定也还没明确，希望不需要重新搞word

**Comment by YanMing-lxb** [comment]
其实按理来说完全不需要提交 word ，所以说我感觉很大概率那个窗口是或选项，盲审也不需要可编辑文档。谢谢你告诉我

昨天我在 GitHub 上发现一个 LaTeX 转 word 的仓库，你可以在我的 start 里面找找，试试。
另外我用 Python 写了一个编译 latex 的工具 PYTeXMK，发布到 pypi 上，感兴趣的话可以尝试一下。

**Comment by QiangzhenZhu** [comment]
好滴，感谢佬。一条道走到黑了，赌学校可以不交word版本。

**Comment by YanMing-lxb** [comment]
盲审应该没问题，最不济，可能辛苦自己通宵排版一下

**Comment by QiangzhenZhu** [comment]
嗯呐

**Comment by sudhua** [comment]
> 嗯呐

佬，想问下，最后只交PDF是可以的吗？

**Comment by YanMing-lxb** [comment]
可以的，今年毕业的我师弟，就是提交了

**Comment by sudhua** [comment]
> 可以的，今年毕业的我师弟，就是提交了

好的 感谢！
