### ISSUE TITLE
请教《桂林电子科技大学本硕博(非全，在职)毕业论文(设计)LaTeX模板 v0.9》当中的正文字体是否均为满足桂电学校官网给出的字体，例如正文为宋体小四等条件？

### ISSUE THREAD

**Issue by 13est-Wishes** [YanMing-lxb/GUET_Thesis_LaTeX#18]
请教一下在《桂林电子科技大学本硕博(非全，在职)毕业论文(设计)LaTeX模板 v0.9》当中的正文字体是否均为满足桂电学校官网给出的字体，例如正文为宋体小四等条件？
附上桂电官网链接：https://www.guet.edu.cn/gra/2022/0223/c6081a7844/page.htm

**Comment by YanMing-lxb** [comment]
符合的，我去年就是用该模板毕业的
另外我建议使用最新版本的，最新版本支持盲审封面自动切换，个人成果中个人信息自动隐藏的功能
最新版本与旧版的最大区别是参考文献使用biblatex，只要参考文献bib文件，替换一下即可

**Comment by YanMing-lxb** [comment]
另外我写了一个 Python 命令行工具，用于编译，你也可以尝试一下 pip install pytexmk
使用的时候就，在终端打开项目地址，输入 pytexmk 即可编译

**Comment by 13est-Wishes** [comment]
好的好的，非常感谢UP的解答，但是因为我们这一届改用了研究生新系统，问了教学秘书说可能还是需要准备word版和PDF版本，所以现在很头痛，把overleaf的PDF版本转word感觉很多格式包括字体间距都有问题

**Comment by YanMing-lxb** [comment]
啊，这也太难受了。这样的话，你只能从头排版了，用pandoc把文字内容提取出来，或者试试wps的pdf转word。

**Comment by YanMing-lxb** [comment]
不过我想一个问题，我去年系统里好像也是有两个选项，一个是 word 一个是 PDF。
有没有一种可能，是不是教学秘书现在也没搞清楚这个系统，所以他为了保险起见跟你说要 word。要不你还是去找真正管这个的问问。重新排班的话工作量太大了。
如果有消息的话，也告诉我一下

**Comment by 13est-Wishes** [comment]
用WPS转word试过了会乱套，跟自己重新排版没太大区别。关于你说的第二点我也是认同的，因为这个新系统是从我们这一届开始实行的，我也找到了去年毕业生的文件是限定了PDF版的。我把我们年级群里刘宇辉老师发的通消息通知给你看。

各位同学，近期有不少学生咨询最终提交的盲审论文版本是PDF还是WORD或者两个都提交，有很多同学都是使用的latex来写学位论文，目前根据新系统上的界面显示是有PDF和WORD两个版本都要提交的地方，所以在正式通知还未下发之前请同学们提前准备好word和PDF两个版本的盲审论文，盲审封面请在研究生院官网下载，谢谢。@全体成员

虽然现在也不确定这个系统到底最后需要什么版本，但是4月初我们就要提交论文审查了，在3月份肯定是要给导师来回改几个版本的，因此不敢冒这个险来赌他最后是PDF版。

**Comment by YanMing-lxb** [comment]
谢谢你的回复，你说得是对的，还是先准备好 word 版本，至于 LaTeX 的就等官方的回复。

还有一点，我猜 overleaf 转 word 应该也是调用的 pandoc ，而使用 pandoc 工具转 word ，要注意图片格式，建议先把图片都转换成 jpg.这样转换后图片的问题应该会少一些。希望能够帮助到你
