### ISSUE TITLE
生成的pdf，目录章节后有空白页问题。

### ISSUE THREAD

**Issue by QiangzhenZhu** [YanMing-lxb/GUET_Thesis_LaTeX#19]
您好，在中英文摘要加起来有3页的情况下，生成的pdf，目录章节后会有空白页，不知此种情况是否合理？学长帮忙看下，这是我的论文textpage链接，方便老哥排查问题

**Comment by QiangzhenZhu** [comment]
<img width="491" alt="1711100514898" src="https://github.com/YanMing-lxb/GUET_Thesis_LaTeX/assets/31847579/1cc9c8ac-8b94-4b1d-bebe-a525e5d58af8">

**Comment by YanMing-lxb** [comment]
已经解决了，github上下载吧，替换cls文件即可，下次不要发你的论文链接了<吓人>(私发邮箱也行啊，别公开)，我都怕你论文漏出去。
其实是老问题了，之前一直不会解决，今天解决了

**Comment by QiangzhenZhu** [comment]
好的，感谢老哥，我把链接关闭了
