### ISSUE TITLE
目录超过10小节，出现字体对齐问题

### ISSUE THREAD

**Issue by RGuanglong** [YanMing-lxb/GUET_Thesis_LaTeX#20]
![image](https://github.com/YanMing-lxb/GUET_Thesis_LaTeX/assets/113451940/11f4dc3e-f98d-4500-a244-c3898aa22d1b)

**Comment by YanMing-lxb** [comment]
我目前在外地不太方便，等我过几天回去看看咋回事

**Comment by YanMing-lxb** [comment]
已经解决了，请使用 v 2.9.1 版本
