### ISSUE TITLE
没有显示参考文献

### ISSUE THREAD

**Issue by curme-miller** [YanMing-lxb/GUET_Thesis_LaTeX#21]
[main.pdf](https://github.com/YanMing-lxb/GUET_Thesis_LaTeX/files/14832523/main.pdf)

**Comment by YanMing-lxb** [comment]
latex 编译是需要进行多次编译的。以该模板为例，需要进行 xelatex --> biber --> makindex --> xelatex --> xelatex 编译，共进行六次编译。如果只进行一次编译肯定不会得到正确的结果，可以试试 pytexmk 可以自动识别当前项目需要的编次次数（pytexmk 算是我重复造轮子了）并按顺序进行自动编译。你现在遇到的问题，应该在阅读以下内容后能够解决。

推荐以下内容：

VSCode中配置latex（包括 latexmk 的配置）： YM-VSCode-Configurations-for-LaTeX；

latex的编译： LaTeX文档多次编译问题详解。

**Comment by curme-miller** [comment]
谢谢  已经好了
