### ISSUE TITLE
今年学位论文封面和盲审论文封面，有变化，老哥有时间更新下吗

### ISSUE THREAD

**Issue by QiangzhenZhu** [YanMing-lxb/GUET_Thesis_LaTeX#22]
各位导师，请注意研究生院更新了研究生学位论文封面、盲审学位论文封面，请提醒学生采用最新封面，本次送审提交的论文请使用盲审学位论文封面，谢谢。@全体成员 
研究生学位论文封面https://www.guet.edu.cn/gra/2022/1101/c6081a7882/page.htm 
盲审学位论文封面https://www.guet.edu.cn/gra/2022/1021/c6081a7852/page.htm

感谢感谢~~~~

**Comment by YanMing-lxb** [comment]
好的，晚上我回去看看

**Comment by YanMing-lxb** [comment]
已解决，请更新
