### ISSUE TITLE
致谢最后的日期中的中文符文〇显示不出来，能解决一下吗

### ISSUE THREAD

**Issue by Redamancyer** [YanMing-lxb/GUET_Thesis_LaTeX#23]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by YanMing-lxb** [comment]
你是在那个系统上编译的？请给一个具体的信息

**Comment by Redamancyer** [comment]
overleaf上的，你没发现你的模板里面都没显示出来吗，那个二0⃣️的那个0⃣️，我已经解决了，使用simsun.ttf即可解决

**Comment by Redamancyer** [comment]
但是新的问题来了，我从1.几的版本过渡到你的最新的模版改修后我一直编译超时，但在texpage上没有任何问题

**Comment by YanMing-lxb** [comment]
overleaf的免费编译时长已经不足一分钟了，建议本地配置latex

**Comment by Redamancyer** [comment]
请问有配置本地的教程吗

**Comment by YanMing-lxb** [comment]
本地配置的教程：[YM-VSCode-Configurations-for-LaTeX](https://github.com/YanMing-lxb/YM-VSCode-Configurations-for-LaTeX)

**Comment by Redamancyer** [comment]
感谢🙏
