### ISSUE TITLE
最新的2.10版本的我再texpage中的修改Accomplish.bib的内容对生成的pdf不构成影响

### ISSUE THREAD

**Issue by Redamancyer** [YanMing-lxb/GUET_Thesis_LaTeX#24]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by YanMing-lxb** [comment]
清除辅助文件够重新试试

**Comment by Redamancyer** [comment]
好的，我关闭了编译缓存就可以了
