### ISSUE TITLE
我自己在mac上搭的Latex进行编译2.10版本的，但是参考文献未被编译和引用，请问这是什么原因呢

### ISSUE THREAD

**Issue by Redamancyer** [YanMing-lxb/GUET_Thesis_LaTeX#25]
{
    "workbench.startupEditor": "none",
    "workbench.colorTheme": "Default Dark+",
    "editor.fontSize": 16,
    "terminal.integrated.defaultProfile.osx": "zsh",
    "files.associations": {
        "*.css": "css"
    },
    "python.defaultInterpreterPath": "/Users/running/miniconda3/envs/st/bin/python",
    "files.autoSave": "afterDelay",
    "launch": {
        "configurations": []
    },
    //------------------------------LaTeX 配置----------------------------------
    // 设置是否自动编译："onSave"当代码被保存时自动编译文件；"never"从不自动编译，即需编写者手动编译文档;"onFileChange"在检测任何依赖项中的文件更改(甚至被其他应用程序修改)时构建项目，即当检测到代码被更改时就自动编译tex文件
    "latex-workshop.latex.autoBuild.run": "onSave",
    //右键菜单,设置是否将编译文档的选项出现在鼠标右键的菜单
    "latex-workshop.showContextMenu": true, //false
    //从使用的包中自动补全命令和环境
    "latex-workshop.intellisense.package.enabled": true,
    //编译出错时设置是否弹出气泡设置
    "latex-workshop.message.error.show": false,
    "latex-workshop.message.warning.show": false,
    // 编译工具和命令
    "latex-workshop.latex.tools": [
        {
            "name": "xelatex",
            "command": "/Library/TeX/texbin/xelatex", //通过终端获取完整路径
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "%DOCFILE%"
            ]
        },
        {
            "name": "pdflatex",
            "command": "/Library/TeX/texbin/pdflatex",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "%DOCFILE%"
            ]
        },
        {
            "name": "latexmk",
            "command": "/Library/TeX/texbin/latexmk",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "-pdf",
                "-outdir=%OUTDIR%",
                "%DOCFILE%"
            ]
        },
        {
            "name": "bibtex",
            "command": "/Library/TeX/texbin/bibtex",
            "args": [
                "%DOCFILE%"
            ]
        }
    ],
    // 用于配置编译链
    //其中name是标签，也就是出现在工具栏中的链名称；tool是name标签所对应的编译顺序
    "latex-workshop.latex.recipes": [
        {
            "name": "PDFLaTeX",
            "tools": [
                "pdflatex"
            ]
        },
        {
            "name": "PDFLaTeX*2",
            "tools": [
                "pdflatex",
                "pdflatex"
            ]
        },
        {
            "name": "XeLaTeX",
            "tools": [
                "xelatex"
            ]
        },
        {
            "name": "BibTeX",
            "tools": [
                "bibtex"
            ]
        },
        {
            "name": "LaTeXmk",
            "tools": [
                "latexmk"
            ]
        },
        {
            "name": "xelatex -> bibtex -> xelatex*2",
            "tools": [
                "xelatex",
                "bibtex",
                "xelatex",
                "xelatex"
            ]
        },
        {
            "name": "pdflatex -> bibtex -> pdflatex*2",
            "tools": [
                "pdflatex",
                "bibtex",
                "pdflatex",
                "pdflatex"
            ]
        }
    ],
    //文件清理。此属性必须是字符串数组
    "latex-workshop.latex.clean.fileTypes": [
        "*.aux",
        "*.bbl",
        "*.blg",
        "*.idx",
        "*.ind",
        "*.lof",
        "*.lot",
        "*.out",
        "*.toc",
        "*.acn",
        "*.acr",
        "*.alg",
        "*.glg",
        "*.glo",
        "*.gls",
        "*.ist",
        "*.fls",
        "*.log",
        "*.fdb_latexmk"
    ],
    //设置为onFaild 在构建失败后清除辅助文件："onFailed"当编译失败时，清除辅助文件；"onBuilt"无论是否编译成功，都选择清除辅助文件；"never"无论何时，都不清除辅助文件
    "latex-workshop.latex.autoClean.run": "onFailed",
    // 使用上次的recipe编译组合
    "latex-workshop.latex.recipe.default": "lastUsed",
    // 用于反向同步的内部查看器的键绑定。ctrl/cmd +点击(默认)或双击
    "latex-workshop.view.pdf.internal.synctex.keybinding": "double-click",
    //Windows使用 SumatraPDF 预览编译好的PDF文件
    // 设置VScode内部查看生成的pdf文件："external"使用外部pdf查看器查看;"tab"使用vscode内置pdf查看器;"browser"使用电脑默认浏览器进行pdf查看
    "latex-workshop.view.pdf.viewer": "external",
    // PDF查看器用于在\ref上的[View on PDF]链接："auto"由编辑器根据情况自动设置;“tabOrBrowser”使用vscode内置pdf查看器或使用电脑默认浏览器进行pdf查看；“external”使用外部pdf查看器查看
    "latex-workshop.view.pdf.ref.viewer": "auto",
    // 使用外部查看器时要执行的命令。此功能不受官方支持。
    "latex-workshop.view.pdf.external.viewer.command": "/Applications/PDF Expert.app", // 注意修改路径
    // 使用外部查看器时，latex-workshop.view.pdf.external.view .command的参数。此功能不受官方支持。%PDF%是用于生成PDF文件的绝对路径的占位符。
    "latex-workshop.view.pdf.external.viewer.args": [
        "%PDF%"
    ],
    // 将synctex转发到外部查看器时要执行的命令。此功能不受官方支持。
    "latex-workshop.view.pdf.external.synctex.command": "/Applications/PDF Expert.app", // 注意修改路径
    // latex-workshop.view.pdf.external.synctex的参数。当同步到外部查看器时。%LINE%是行号，%PDF%是生成PDF文件的绝对路径的占位符，%TEX%是触发syncTeX的扩展名为.tex的LaTeX文件路径。
    "latex-workshop.view.pdf.external.synctex.args": [
        "-forward-search",
        "%TEX%",
        "%LINE%",
        "-reuse-instance",
        "-inverse-search",
        "\"F:/Microsoft VS Code/Code.exe\" \"F:/Microsoft VS Code/resources/app/out/cli.js\" -r -g \"%f:%l\"", // 注意修改路径
        "%PDF%"
    ],
    "latex-workshop.intellisense.biblatexJSON.replace": {},
    "workbench.editorAssociations": {
        "*.pdf": "pdf.preview"
    },
}

**Comment by YanMing-lxb** [comment]
编译问题，请去讨论区看第一条

**Comment by YanMing-lxb** [comment]
另外，请确保你的 bib 文件导出的是 biblatex 类型，外加正文中有引用参考文献

**Comment by Redamancyer** [comment]
好的，解决了，还有最后一个问题哈，我看overleaf上的编译结果pdf只有几兆，远小于其他平台编译的，我猜测可能是图片压缩或者是pdf压缩后的，请问可以在我们本地实现类似效果吗

**Comment by YanMing-lxb** [comment]
你仔细看 main 文件的前沿区，有一段代码是解除压缩的，这是为了提高编译速度而设置的，你在最后提交的时候把这行代码注释掉 PDF 文档就能压缩了。

同志！要好好阅读一下注释啊！都不是白写的😮‍💨
