### ISSUE TITLE
针对符号说明的一些bug

### ISSUE THREAD

**Issue by LattleGrass** [YanMing-lxb/GUET_Thesis_LaTeX#28]
**描述错误**
1.  在符号说明部分，使用$[ \! [$和$] \! ]$是不被允许的，因此使用了$\llbracket$和$\rrbracket$，但这确实不方便，同时可能意味着更多符号的不兼容
2.  同时，目录的符号说明页码事实上为插表索引的页码

**复制**
1.  在符号说明中写入
\nomenclature[A,01]{$[\![ \hat{x}_{i} ]\!]_{j}$}{参数}
运行报错
修改为
\nomenclature[D,13]{$\{\llbracket \ell_{i} \rrbracket_{j}\}_{j \in [1,m]}$}{$\ell_{i}$的秘密分享份额}
可以运行

2. 默认运行即可

**预期行为**
正常执行输出结果

**截图**
暂无

**Comment by LattleGrass** [comment]
未来工作方向中： biblatex 下实现对攻读学位期间取得成果中作者的粗体显示，已实现，可以更新下

**Comment by YanMing-lxb** [comment]
目录的符号说明页码问题已解决
