### ISSUE TITLE
参考文献页眉不一致问题。

### ISSUE THREAD

**Issue by QiangzhenZhu** [YanMing-lxb/GUET_Thesis_LaTeX#30]
老哥，这个问题不知道算不算bug，参考文献页眉需不需要保持一致？谢啦
<img width="524" alt="1717074638266" src="https://github.com/YanMing-lxb/GUET_Thesis_LaTeX/assets/31847579/db89246e-593d-4295-bb4e-c83dda2556a2">
<img width="511" alt="1717074647946" src="https://github.com/YanMing-lxb/GUET_Thesis_LaTeX/assets/31847579/2d4031bb-3784-43e9-b1ba-f5618d560923">

**Comment by YanMing-lxb** [comment]
已经解决，你更新下看看

**Comment by QiangzhenZhu** [comment]
老哥，感谢凌晨的修复，刚试了下，还是这样

**Comment by QiangzhenZhu** [comment]
应该是一个偶发性bug，我舍友的是没问题的

**Comment by YanMing-lxb** [comment]
你看一下，是不是你俩的参考文献第一页的位置不一样 奇数页还是偶数页

**Comment by YanMing-lxb** [comment]
那，你排查一下，是不是cls没更新好，清除一下辅助文件。行不行都反馈给我一下

**Comment by QiangzhenZhu** [comment]
哥们还是不行。文件是有清除的，更换cls后，能看到其他地方的格式是有变化的。

**Comment by YanMing-lxb** [comment]
发给我一个具有该问题的完整样例，我看看咋回事

**Comment by QiangzhenZhu** [comment]
https://www.texpage.com/share/f680313dec1f4e7e927a87b57b787725  ，老哥这个是我的论文，您可以看下，是什么问题导致的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YanMing-lxb/GUET_Thesis_LaTeX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月31日(星期五) 下午5:13
***@***.***&gt;;
抄送:&nbsp;"朱振强 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [YanMing-lxb/GUET_Thesis_LaTeX] 参考文献页眉不一致问题。 (Issue #30)





 
发给我一个具有该问题的完整样例，我看看咋回事

**Comment by YanMing-lxb** [comment]
额，分享链接关闭了，你可以发邮件给我 lxb-yanming@foxmail.com

**Comment by YanMing-lxb** [comment]
已经解决了，另外你的参考文献中 `RN77` 这个key 是重复的，你自行解决一下吧

**Comment by QiangzhenZhu** [comment]
好来，谢谢老哥





------------------ 原始邮件 ------------------
发件人: 焱铭 ***@***.***&gt;
发送时间: 2024年6月8日 13:30
收件人: YanMing-lxb/GUET_Thesis_LaTeX ***@***.***&gt;
抄送: QiangzhenZhu ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [YanMing-lxb/GUET_Thesis_LaTeX] 参考文献页眉不一致问题。 (Issue #30)





 
已经解决了，另外你的参考文献中 RN77 这个key 是重复的，你自行解决一下吧
