### ISSUE TITLE
表格中字体大小设置

### ISSUE THREAD

**Issue by QiangzhenZhu** [YanMing-lxb/GUET_Thesis_LaTeX#34]
哥们，学校给的模板，正文是小四字体，表格中字体要求是五号，本模板中表格字体大小貌似和正文是一致的？这个要怎么设置呀

**Comment by YanMing-lxb** [comment]
你表格用的是什么环境，发一个示例代码给我

**Comment by YanMing-lxb** [comment]
已经解决，你测试看看

**Comment by YanMing-lxb** [comment]
稍等，我回头看一下，最近太忙了

**Comment by YanMing-lxb** [comment]
\centering 可以不加，因为模板默认设置居中。要不 clone 一下最新的模板，试试，最近更新模板了。目前你给我的案例来看字体大小是正确的

![Image](https://github.com/user-attachments/assets/dd6c6ed9-a71c-413c-9be5-d4fb87a6faf8)

**Comment by YanMing-lxb** [comment]
目前更新，可以去试试这个版本：[GUET_Thesis_LaTeX v2.11.6](https://github.com/YanMing-lxb/GUET_Thesis_LaTeX/releases/tag/v2.11.6)

threetab 表格环境字体大小异常我已经解决了
