### ISSUE TITLE
关于latex编译问题

### ISSUE THREAD

**Issue by liuxufeng2016** [YanMing-lxb/GUET_Thesis_LaTeX#35]
latex 编译是需要进行多次编译的。以该模板为例，需要进行 `xelatex` --> `biber` --> `makindex` --> `xelatex` --> `xelatex` 编译，共进行六次编译。
网上还有说F5，F8、F8、F5共4次编译。
我的情况是，编译一次就可以生成pdf。有时候换个模版就不行了。我也没找到切换xelatex 和biber的地方呢？

**Comment by liuxufeng2016** [comment]
![微信截图_20240704172023](https://github.com/YanMing-lxb/GUET_Thesis_LaTeX/assets/85939324/e9621769-636c-4ad6-b322-f3ac1317f065)
我的界面如上图

**Comment by YanMing-lxb** [comment]
这个编译器我没用过所以不太了解怎么配置。你编译的是学位论文模版还是爱思唯尔的模版？两者的编译次数是不一样的

**Comment by liuxufeng2016** [comment]
你好，你的来信已收到，我将尽快给你回复您。谢谢。Hello.Your letter has been received. I will reply to you as soon as possible.Thank you.This is an automatic mail reply.Your message has been delivered successfully。

**Comment by YanMing-lxb** [comment]
可以试试用 vscode 编辑器，我的 GitHub 上有一个关于配置的教程

**Comment by liuxufeng2016** [comment]
是的，我用的是爱思唯尔的模版。

**Comment by YanMing-lxb** [comment]
latex 编译是需要进行多次编译的。以该模板为例，需要进行 xelatex --> biber --> makindex --> xelatex --> xelatex 编译，共进行六次编译。如果只进行一次编译肯定不会得到正确的结果。就是你只编译一次的话论文里的交叉引用是不会编译出来的 ，有交叉引用和参考文献就需要xelatex bibtex或者biber xelatex 四次编译 。

这个三言两语说不清楚，建议你学习一下！
可以看一下这个：https://mp.weixin.qq.com/s/qN64g3Fa44cJBh8ISc7QYw

**Comment by YanMing-lxb** [comment]
F5，F8、F8、F5 只是TeXstudio中对应编译命令的快捷键，还是要学习理解编译逻辑的

**Comment by liuxufeng2016** [comment]
[elsarticle (1).zip](https://github.com/user-attachments/files/16152662/elsarticle.1.zip)
非常感谢您的回答。我用的编译器是TeXstudio，模版是elsarticle爱思唯尔期刊Latex模版。因为每次编译都只进行了一次F5，参考文献、图表公式序号都是正常的。只是引用的序号和参考文献没有链接。
我研究没有那么深，并不是很关心其中的逻辑。只想请教下正确的操作是按哪些键，或菜单，以及正确编译后的效果是怎么判断的？

**Comment by liuxufeng2016** [comment]
> [elsarticle (1).zip](https://github.com/user-attachments/files/16152662/elsarticle.1.zip) 非常感谢您的回答。我用的编译器是TeXstudio，模版是elsarticle爱思唯尔期刊Latex模版。因为每次编译都只进行了一次F5，参考文献、图表公式序号都是正常的。只是引用的序号和参考文献没有链接。 我研究没有那么深，并不是很关心其中的逻辑。只想请教下正确的操作是按哪些键，或菜单，以及正确编译后的效果是怎么判断的？

上面链接的就是爱思唯尔期刊Latex模版。

**Comment by liuxufeng2016** [comment]
你好，你的来信已收到，我将尽快给你回复您。谢谢。Hello.Your letter has been received. I will reply to you as soon as possible.Thank you.This is an automatic mail reply.Your message has been delivered successfully。
