### ISSUE TITLE
GUET dissertations now require uploading PDF and WORD text versions

### ISSUE THREAD

**Issue by sudhua** [YanMing-lxb/GUET_Thesis_LaTeX#37]
Hello Senior, I've been following this project for quite a while. Currently, GUET requires the degree thesis to be submitted in both PDF and Word formats. I'm now considering whether to write my thesis using LaTeX or Word. I understand that converting from LaTeX to Word may not result in a fully accurate conversion. Does that make it more troublesome to use LaTeX for writing the thesis?
Do you have any better suggestions, Senior?
Thanks!

![image](https://github.com/user-attachments/assets/dabb8457-4a18-45e7-a8f7-ad4f751c6511)

**Comment by YanMing-lxb** [comment]
是这样的，我的学位论文和我师弟24届毕业的一个师弟都是用latex写的，使用latex提交论文的话就是提交pdf文件即可，不用提交word。所以说不用考虑转换的问题，查重的话直接用pdf查重就行。整个流程应该是没有问题的。另外请问你的研究生还是本科？

**Comment by sudhua** [comment]
好的，感谢师兄解惑。我是研究生。

**Comment by YanMing-lxb** [comment]
好的
