### ISSUE TITLE
Latex无法生成参考文献页面，报错 I found no \bibstyle & \bibdata & \citation command

### ISSUE THREAD

**Issue by liuxufeng2016** [YanMing-lxb/GUET_Thesis_LaTeX#39]
我已经按这个连接：https://blog.csdn.net/weixin_53011291/article/details/139034367，修改了编译顺序为xelatex--biber--xelatex*2
依然报错： I found no \bibstyle & \bibdata & \citation command。运行最新模版GUET_Thesis_LaTeX-main依然有相同问题。能否给个解决方法或思路？谢谢
![111](https://github.com/user-attachments/assets/74c00e9d-c1fc-45b5-aff3-25e94f5b6de0)

**Comment by YanMing-lxb** [comment]
log文件发给我看一下，另外bib文件有没有对应的更新

**Comment by liuxufeng2016** [comment]
你好，你的来信已收到，我将尽快给你回复您。谢谢。Hello.Your letter has been received. I will reply to you as soon as possible.Thank you.This is an automatic mail reply.Your message has been delivered successfully。

**Comment by liuxufeng2016** [comment]
> log文件发给我看一下，另外bib文件有没有对应的更新

非常感谢您的回答。bib文件已经更新过了。log文件我没的找到，文件目录如下。

![Uploading 0000.png…]()

但有点奇怪，啥都没有修改，今天打开编译您上传的模版，突然不报错了。但编译我的论文出现新问题，即，先前编译参考文献是正确的。今天增加了几条参考文献，编译后PDF中的引用是文献key本身。截图如下：
![问题](https://github.com/user-attachments/assets/398a2e35-29f3-4215-a113-301f704e4bec)
我怀疑是bib中文献格式问题，采用了Bibtex到bibitem转换器转化了格式，发现似乎不是bibitem方式。

**Comment by YanMing-lxb** [comment]
参考文献的格式是biblatex，如果你的参考文献是直接在网页上复制下来的，那大概率复制下来的是bibtex格式，所以我建议用zotero导出biblatex格式，或者你将从网页上复制下来的bibtex格式的bib文件用pandoc转换成biblatex格式

**Comment by YanMing-lxb** [comment]
另外你的文件目录的这个图片没有成功上传，我看不见，日志文件没有，应该是你在latex workshop 中开启了自动清理辅助文件的功能了。
你可以试试用 pytexmk 来编译
电脑装好python 后 cmd 终端输入 pip install pytexmk
具体教程你看 https://github.com/YanMing-lxb/PyTeXMK

**Comment by liuxufeng2016** [comment]
非常感谢您的回复，给了我很大的启发以及修改方向。但下午又出现了，开始的3个报错： I found no \bibstyle & \bibdata & \citation command
以下是运行界面包括报错提示截图、目录截图
![运行界面截图](https://github.com/user-attachments/assets/0fedfe23-1135-4292-a853-30c3d4e886f2)
![文件目录截图](https://github.com/user-attachments/assets/bc2ecd30-4006-42a1-bda2-40f601fdf636)
其实就是您上传的模版，没有做改动。我的配置文件也一起上传了，注释了自动清理辅助文件，还是没有生成日志文件log.
[seetingjso.txt](https://github.c


[GUET_Thesis_LaTeX-main (1).zip](https://github.com/user-attachments/files/18217867/GUET_Thesis_LaTeX-main.1.zip)

**Comment by YanMing-lxb** [comment]
应该是latexmk 自动清除了辅助文件，你可以看看，或者直接用pytexmk
另外，你发给我的这个我编译了，没有发现问题啊

**Comment by YanMing-lxb** [comment]
主要是有些问题，看log文件比较容易排查发现

**Comment by liuxufeng2016** [comment]
> 应该是latexmk 自动清除了辅助文件，你可以看看，或者直接用pytexmk 另外，你发给我的这个我编译了，没有发现问题啊

再次感谢您的帮忙。我安装了python，且latexmk 以及pytexmk两种方法我都尝试过了，可能是环境不同或参数设置问题，很遗憾都无功而返。或许可以称之为，您说的和我想的不在一个频道上吧。鉴于此，可以加您微信吗？我的微信号发通过邮箱（notifications@github.com）发给您。

**Comment by YanMing-lxb** [comment]
发给我吧，咱们加个微信看一下

**Comment by YanMing-lxb** [comment]
GitHub 主页上有我的邮箱

**Comment by liuxufeng2016** [comment]
尊敬的燚铭：
再次感谢您的帮忙。我安装了python，且latexmk 以及pytexmk两种方法我都尝试过了，可能是环境不同或参数设置问题，很遗憾都无功而返。或许可以称之为，您说的和我想的不在一个频道上吧。鉴于此，可以加您微信吗？我的微信号：13977926254



谢谢
再次感谢您的帮忙。我安装了python，且latexmk ***@***.***）发给您。

刘旭锋
***@***.***



&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YanMing-lxb/GUET_Thesis_LaTeX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月21日(星期六) 晚上6:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YanMing-lxb/GUET_Thesis_LaTeX] Latex无法生成参考文献页面，报错 I found no \bibstyle &amp; \bibdata &amp; \citation command (Issue #39)





 
应该是latexmk 自动清除了辅助文件，你可以看看，或者直接用pytexmk
 另外，你发给我的这个我编译了，没有发现问题啊
